#!/bin/bash
# Ketto: set up the sharing backend on your own Cloudflare account.
#
# Ketto writes this script (Settings > Sharing) next to the files it needs:
#   config.env     the domain, bucket name and Worker name you chose in Ketto
#   secret.txt     the token Ketto uses to authenticate; generated by Ketto and kept in your Keychain
#   wrangler.json  the Worker configuration
#   worker.js      the Worker itself
#
# The prompt Ketto gives you for your coding agent spells out the same steps and points
# here as the short route; the script also runs on its own in Terminal.
#
# What it does, in order: creates a private R2 bucket, gives it a rule that deletes videos
# after three days, deploys the Worker on your domain, and stores the token in the Worker.
# Nothing else on the account is touched. Every step is safe to repeat, so re-running the
# script after a failure is fine.
#
# Needs wrangler 4 or newer, logged in (`wrangler login`) to the Cloudflare account that
# already holds the domain.
set -euo pipefail
cd "$(dirname "$0")"

# shellcheck disable=SC1091
source ./config.env
: "${KETTO_DOMAIN:?config.env is missing KETTO_DOMAIN}"
: "${KETTO_BUCKET:?config.env is missing KETTO_BUCKET}"
: "${KETTO_WORKER:?config.env is missing KETTO_WORKER}"

step() { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
fail() { printf '\n\033[31mSetup failed:\033[0m %s\n' "$*" >&2; exit 1; }

step "Checking wrangler"
command -v wrangler >/dev/null 2>&1 || fail "wrangler is not installed. Install it (https://developers.cloudflare.com/workers/wrangler/install-and-update/), run 'wrangler login', then run this command again."
WRANGLER_VERSION="$(wrangler --version 2>/dev/null | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1 || true)"
WRANGLER_MAJOR="${WRANGLER_VERSION%%.*}"
if [ -z "$WRANGLER_MAJOR" ] || [ "$WRANGLER_MAJOR" -lt 4 ]; then
  fail "wrangler ${WRANGLER_VERSION:-(unknown version)} is too old; 4.0 or newer is required. Update it with 'npm install -g wrangler@latest' (or 'brew upgrade cloudflare-wrangler' if Homebrew installed it) and run this command again."
fi
echo "wrangler $WRANGLER_VERSION"

step "Checking the Cloudflare login"
if wrangler whoami 2>&1 | grep -qi 'not authenticated'; then
  fail "wrangler is not logged in. Run 'wrangler login', then run this command again."
fi

step "Creating the R2 bucket '$KETTO_BUCKET'"
if wrangler r2 bucket info "$KETTO_BUCKET" >/dev/null 2>&1; then
  echo "The bucket already exists; keeping it."
else
  wrangler r2 bucket create "$KETTO_BUCKET"
fi

step "Adding the three-day expiry rule to the bucket"
if LIFECYCLE_OUTPUT="$(wrangler r2 bucket lifecycle add "$KETTO_BUCKET" ketto-expire --expire-days 3 --abort-multipart-days 1 --force 2>&1)"; then
  printf '%s\n' "$LIFECYCLE_OUTPUT"
elif grep -qi 'already' <<<"$LIFECYCLE_OUTPUT"; then
  echo "The rule is already in place."
else
  printf '%s\n' "$LIFECYCLE_OUTPUT"
  fail "Could not add the lifecycle rule to '$KETTO_BUCKET'."
fi

step "Deploying the Worker '$KETTO_WORKER' to https://$KETTO_DOMAIN"
wrangler deploy

step "Storing Ketto's token in the Worker"
[ -s ./secret.txt ] || fail "secret.txt is missing. In Ketto, open Settings > Sharing and start the setup again."
wrangler secret put KETTO_TOKEN < ./secret.txt

printf '\n\033[32mDone.\033[0m The sharing backend is live at https://%s\n' "$KETTO_DOMAIN"
echo "Ketto connects on its own within a few seconds (Settings > Sharing). A brand-new domain can take a minute or two while Cloudflare issues its certificate."
