/**
 * Ketto sharing backend: one Cloudflare Worker in front of a private R2 bucket.
 *
 * Ketto writes this file next to setup.sh and deploys it with wrangler on the user's own
 * Cloudflare account. Finished exports are uploaded here as multipart parts; viewers get
 * links to /v/<id>. The bucket is never public, so only this Worker reads or writes it, and
 * only callers holding KETTO_TOKEN can write. A lifecycle rule on the bucket (set up by
 * setup.sh) deletes objects about three days after upload.
 *
 * Bindings: VIDEOS (R2 bucket), BUCKET_NAME (var, informational),
 *           KETTO_TOKEN (secret, 64 hex chars generated by the app).
 *
 * Contract, API_VERSION 1. Routes marked "auth" need `Authorization: Bearer <KETTO_TOKEN>`.
 *
 *   GET    /                                      { service, api }
 *   GET    /api/status                            auth  { ok, api, bucket }
 *   POST   /api/uploads                           auth  { title, filename, size, contentType }
 *                                                       -> 201 { id, uploadId, partSize }
 *   PUT    /api/uploads/:id/:uploadId/:partNumber auth  raw part body -> { partNumber, etag }
 *                                                       (every part except the last must be
 *                                                       exactly partSize bytes)
 *   POST   /api/uploads/:id/:uploadId/complete    auth  { parts: [{ partNumber, etag }] }
 *                                                       -> 201 { id, title, size, uploaded, expires, url }
 *   DELETE /api/uploads/:id/:uploadId             auth  abort -> 204
 *   GET    /api/videos                            auth  { videos: [{ id, title, size, uploaded, expires, url }] }
 *   DELETE /api/videos/:id                        auth  -> 204
 *   GET    /v/:id  and  /f/:id                          the video, Range requests honoured.
 *                                                       /v is the share link; /f will keep
 *                                                       serving the raw file once /v becomes
 *                                                       an HTML viewer.
 *
 * Errors are JSON `{ error }` with a matching status. Anything under /api answers 503 while
 * KETTO_TOKEN is not set (between `wrangler deploy` and `wrangler secret put`).
 */

const API_VERSION = 1;
/** Bytes per multipart part. Under the 100 MB Worker request-body limit on every plan and a
 *  multiple of 5 MiB, which is R2's minimum part size. The app uses this value verbatim. */
const PART_SIZE = 32 * 1024 * 1024;
const MAX_PART_BYTES = 95 * 1024 * 1024;
/** Matches the lifecycle rule setup.sh puts on the bucket. Only used to tell the app when a
 *  link will stop working; R2 does the deleting. */
const TTL_MS = 3 * 24 * 60 * 60 * 1000;
const KEY_PREFIX = "videos/";
const ID_PATTERN = "[a-z2-7]{26}";
const BASE32 = "abcdefghijklmnopqrstuvwxyz234567";

const routes = [
  ["GET", /^\/$/, () => json({ service: "ketto-share", api: API_VERSION })],
  ["HEAD", /^\/$/, () => json({ service: "ketto-share", api: API_VERSION })],
  ["GET", new RegExp(`^/(?:v|f)/(${ID_PATTERN})$`), serveVideo],
  ["HEAD", new RegExp(`^/(?:v|f)/(${ID_PATTERN})$`), serveVideo],
  ["GET", /^\/api\/status$/, status, "auth"],
  ["POST", /^\/api\/uploads$/, createUpload, "auth"],
  ["PUT", new RegExp(`^/api/uploads/(${ID_PATTERN})/([^/]+)/(\\d+)$`), uploadPart, "auth"],
  ["POST", new RegExp(`^/api/uploads/(${ID_PATTERN})/([^/]+)/complete$`), completeUpload, "auth"],
  ["DELETE", new RegExp(`^/api/uploads/(${ID_PATTERN})/([^/]+)$`), abortUpload, "auth"],
  ["GET", /^\/api\/videos$/, listVideos, "auth"],
  ["DELETE", new RegExp(`^/api/videos/(${ID_PATTERN})$`), deleteVideo, "auth"],
];

export default {
  async fetch(request, env) {
    try {
      return await route(request, env);
    } catch (error) {
      console.error("ketto-share:", error);
      return json({ error: "Internal error" }, 500);
    }
  },
};

async function route(request, env) {
  const url = new URL(request.url);
  for (const [method, pattern, handler, auth] of routes) {
    if (request.method !== method) continue;
    const match = url.pathname.match(pattern);
    if (!match) continue;
    if (auth) {
      const denied = await authorize(request, env);
      if (denied) return denied;
    }
    const params = match.slice(1).map(decodeURIComponent);
    return handler({ request, env, url }, ...params);
  }
  return json({ error: "Not found" }, 404);
}

// MARK: - Authentication

async function authorize(request, env) {
  if (!env.KETTO_TOKEN) {
    return json({ error: "The backend has no token yet. Finish the Ketto setup command (it runs `wrangler secret put KETTO_TOKEN`)." }, 503);
  }
  const header = request.headers.get("Authorization") || "";
  const presented = header.startsWith("Bearer ") ? header.slice("Bearer ".length).trim() : "";
  if (!presented || !(await tokensMatch(presented, env.KETTO_TOKEN))) {
    return json({ error: "Unauthorized" }, 401);
  }
  return null;
}

/** Constant-time comparison. Hashing first gives equal-length inputs whatever was presented. */
async function tokensMatch(presented, expected) {
  const encoder = new TextEncoder();
  const [a, b] = await Promise.all([
    crypto.subtle.digest("SHA-256", encoder.encode(presented)),
    crypto.subtle.digest("SHA-256", encoder.encode(expected)),
  ]);
  return crypto.subtle.timingSafeEqual(a, b);
}

// MARK: - API

function status({ env }) {
  return json({ ok: true, api: API_VERSION, bucket: env.BUCKET_NAME || null });
}

async function createUpload({ request, env }) {
  const body = await readJSON(request);
  if (!body) return json({ error: "Expected a JSON body" }, 400);
  const size = Number(body.size);
  if (!Number.isInteger(size) || size <= 0) return json({ error: "size must be a positive integer" }, 400);
  const title = cleanTitle(body.title);
  const filename = typeof body.filename === "string" && body.filename.trim() ? body.filename.trim().slice(0, 200) : `${title}.mp4`;
  const contentType = typeof body.contentType === "string" && body.contentType.startsWith("video/") ? body.contentType : "video/mp4";
  const id = newID();
  const upload = await env.VIDEOS.createMultipartUpload(keyFor(id), {
    httpMetadata: { contentType },
    customMetadata: { title, filename, size: String(size) },
  });
  return json({ id, uploadId: upload.uploadId, partSize: PART_SIZE }, 201);
}

async function uploadPart({ request, env }, id, uploadId, partNumberText) {
  const partNumber = Number(partNumberText);
  const declared = Number(request.headers.get("Content-Length"));
  let refusal = null;
  if (!Number.isInteger(partNumber) || partNumber < 1 || partNumber > 10000) {
    refusal = json({ error: "partNumber must be between 1 and 10000" }, 400);
  } else if (!request.body) {
    refusal = json({ error: "Missing part body" }, 400);
  } else if (Number.isFinite(declared) && declared > MAX_PART_BYTES) {
    refusal = json({ error: `A part may not exceed ${MAX_PART_BYTES} bytes` }, 413);
  }
  if (refusal) {
    // Answering without reading the body would leave the runtime to cancel the stream noisily.
    if (request.body) request.body.cancel().catch(() => {});
    return refusal;
  }
  const upload = env.VIDEOS.resumeMultipartUpload(keyFor(id), uploadId);
  try {
    const part = await upload.uploadPart(partNumber, request.body);
    return json({ partNumber: part.partNumber, etag: part.etag });
  } catch (error) {
    return storageError("Uploading the part failed", error);
  }
}

async function completeUpload({ request, env, url }, id, uploadId) {
  const body = await readJSON(request);
  const parts = body && Array.isArray(body.parts) ? body.parts : null;
  if (!parts || parts.length === 0) return json({ error: "parts must be a non-empty array" }, 400);
  const normalized = parts.map((part) => ({ partNumber: Number(part && part.partNumber), etag: String((part && part.etag) || "") }));
  if (normalized.some((part) => !Number.isInteger(part.partNumber) || part.partNumber < 1 || !part.etag)) {
    return json({ error: "Every part needs a partNumber and an etag" }, 400);
  }
  const upload = env.VIDEOS.resumeMultipartUpload(keyFor(id), uploadId);
  let object;
  try {
    object = await upload.complete(normalized);
  } catch (error) {
    return storageError("Completing the upload failed", error);
  }
  return json(describe(object, url.origin), 201);
}

async function abortUpload({ env }, id, uploadId) {
  const upload = env.VIDEOS.resumeMultipartUpload(keyFor(id), uploadId);
  try {
    await upload.abort();
  } catch (error) {
    return storageError("Aborting the upload failed", error);
  }
  return new Response(null, { status: 204 });
}

async function listVideos({ env, url }) {
  const videos = [];
  let cursor;
  do {
    const page = await env.VIDEOS.list({ prefix: KEY_PREFIX, include: ["customMetadata"], cursor, limit: 1000 });
    for (const object of page.objects) {
      if (idFrom(object.key)) videos.push(describe(object, url.origin));
    }
    cursor = page.truncated ? page.cursor : undefined;
  } while (cursor);
  videos.sort((a, b) => (a.uploaded < b.uploaded ? 1 : a.uploaded > b.uploaded ? -1 : 0));
  return json({ videos });
}

async function deleteVideo({ env }, id) {
  const key = keyFor(id);
  if (!(await env.VIDEOS.head(key))) return json({ error: "No such video" }, 404);
  await env.VIDEOS.delete(key);
  return new Response(null, { status: 204 });
}

// MARK: - Serving

async function serveVideo({ request, env }, id) {
  const key = keyFor(id);
  if (request.method === "HEAD") {
    const head = await env.VIDEOS.head(key);
    if (!head) return notFoundPage();
    const headers = videoHeaders(head);
    headers.set("Content-Length", String(head.size));
    return new Response(null, { status: 200, headers });
  }

  // R2 normalises the Range header itself, but it also reports a range for a plain GET and quietly serves
  // the whole object for a range it cannot satisfy, so the header is parsed here as well: to know whether the
  // request was partial at all, and for the 416 case.
  const requested = parseRange(request.headers.get("Range"));
  const options = { onlyIf: request.headers };
  if (requested) options.range = request.headers;
  const object = await env.VIDEOS.get(key, options);
  if (!object) return notFoundPage();

  const headers = videoHeaders(object);
  if (!object.body) {
    // Precondition (If-None-Match / If-Modified-Since) not met: metadata only, no body.
    return new Response(null, { status: 304, headers });
  }
  if (requested && !isSatisfiable(requested, object.size)) {
    // R2 served the whole object for the bad range; drop its stream quietly instead of leaking it.
    object.body.cancel().catch(() => {});
    headers.set("Content-Range", `bytes */${object.size}`);
    headers.set("Cache-Control", "no-store");
    return new Response(null, { status: 416, headers });
  }
  if (requested && object.range) {
    const { start, end } = resolveRange(object.range, object.size);
    headers.set("Content-Range", `bytes ${start}-${end}/${object.size}`);
    headers.set("Content-Length", String(end - start + 1));
    return new Response(object.body, { status: 206, headers });
  }
  headers.set("Content-Length", String(object.size));
  return new Response(object.body, { status: 200, headers });
}

/** One byte range as `{ offset, end }` or `{ suffix }`; null when absent, malformed or multi-range (then the
 *  whole object is served, as the RFC allows). */
function parseRange(header) {
  if (!header) return null;
  const match = /^\s*bytes\s*=\s*(\d*)\s*-\s*(\d*)\s*$/.exec(header);
  if (!match) return null;
  const [, startText, endText] = match;
  if (startText === "" && endText === "") return null;
  if (startText === "") return { suffix: Number(endText) };
  const offset = Number(startText);
  const end = endText === "" ? undefined : Number(endText);
  if (end !== undefined && end < offset) return null;
  return { offset, end };
}

function isSatisfiable(range, size) {
  if (range.suffix !== undefined) return range.suffix > 0 && size > 0;
  return range.offset < size;
}

/** R2 hands back the range it actually served, already clamped to the object. */
function resolveRange(range, size) {
  if (range.suffix !== undefined) {
    const start = Math.max(size - range.suffix, 0);
    return { start, end: size - 1 };
  }
  const start = range.offset || 0;
  const end = range.length !== undefined ? start + range.length - 1 : size - 1;
  return { start, end: Math.min(end, size - 1) };
}

function videoHeaders(object) {
  const headers = new Headers();
  object.writeHttpMetadata(headers);
  if (!headers.has("Content-Type")) headers.set("Content-Type", "video/mp4");
  headers.set("ETag", object.httpEtag);
  headers.set("Last-Modified", object.uploaded.toUTCString());
  headers.set("Accept-Ranges", "bytes");
  headers.set("Cache-Control", "public, max-age=3600");
  headers.set("X-Content-Type-Options", "nosniff");
  const title = (object.customMetadata && object.customMetadata.title) || "video";
  headers.set("Content-Disposition", `inline; filename="${asciiFilename(title)}.mp4"; filename*=UTF-8''${encodeURIComponent(title)}.mp4`);
  return headers;
}

function notFoundPage() {
  const html = `<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Video not available</title>
<style>
  body { font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: #1c1c1e; background: #f2f2f7; margin: 0; }
  main { max-width: 32rem; margin: 20vh auto; padding: 2rem; background: #fff; border-radius: 16px; }
  h1 { font-size: 1.25rem; margin: 0 0 .5rem; }
  p { margin: 0; color: #6e6e73; }
</style>
<main>
  <h1>This video isn't available</h1>
  <p>Ketto share links stop working about three days after the video was shared, or sooner if the owner removed it.</p>
</main>
`;
  return new Response(html, { status: 404, headers: { "Content-Type": "text/html; charset=utf-8", "Cache-Control": "no-store" } });
}

// MARK: - Helpers

function keyFor(id) {
  return `${KEY_PREFIX}${id}.mp4`;
}

function idFrom(key) {
  const match = key.match(new RegExp(`^${KEY_PREFIX}(${ID_PATTERN})\\.mp4$`));
  return match ? match[1] : null;
}

function describe(object, origin) {
  const id = idFrom(object.key);
  const meta = object.customMetadata || {};
  const uploaded = object.uploaded instanceof Date ? object.uploaded : new Date(object.uploaded);
  return {
    id,
    title: meta.title || "Untitled",
    size: object.size,
    uploaded: uploaded.toISOString(),
    expires: new Date(uploaded.getTime() + TTL_MS).toISOString(),
    url: `${origin}/v/${id}`,
  };
}

/** 128 random bits as 26 lowercase base32 characters: URL-safe, case-insensitive, unguessable. */
function newID() {
  const bytes = crypto.getRandomValues(new Uint8Array(16));
  let bits = 0;
  let value = 0;
  let out = "";
  for (const byte of bytes) {
    value = ((value << 8) | byte) >>> 0;
    bits += 8;
    while (bits >= 5) {
      out += BASE32[(value >>> (bits - 5)) & 31];
      bits -= 5;
    }
  }
  if (bits > 0) out += BASE32[(value << (5 - bits)) & 31];
  return out;
}

function cleanTitle(value) {
  if (typeof value !== "string") return "Untitled";
  const cleaned = value.replace(/[\x00-\x1f\x7f]/g, " ").replace(/\s+/g, " ").trim().slice(0, 120);
  return cleaned || "Untitled";
}

function asciiFilename(title) {
  const cleaned = title.replace(/[^A-Za-z0-9 ._-]/g, "_").replace(/\s+/g, " ").trim();
  return cleaned || "video";
}

async function readJSON(request) {
  try {
    const value = await request.json();
    return value && typeof value === "object" && !Array.isArray(value) ? value : null;
  } catch {
    return null;
  }
}

function storageError(prefix, error) {
  const message = error && error.message ? error.message : String(error);
  // R2 reports both client mistakes (bad part size, unknown upload) and transient trouble
  // through thrown errors. 502 keeps the app retrying only for the transient kind after it has
  // given up on the request as a whole.
  const clientMistake = /part|upload|not found|does not exist|invalid/i.test(message);
  return json({ error: `${prefix}: ${message}` }, clientMistake ? 400 : 502);
}

function json(data, status = 200) {
  return new Response(JSON.stringify(data), {
    status,
    headers: { "Content-Type": "application/json; charset=utf-8", "Cache-Control": "no-store" },
  });
}
